name: haskell-scaffold
author: Nikolai Paul <nikolai.paul@zenex.de>
version: 0.0.0
license: MIT

dependencies:
- base
- protolude

executables:
  haskell-scaffold:
    source-dirs: src
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wredundant-constraints
    default-extensions:
      - NoImplicitPrelude
      - OverloadedStrings
      - NamedFieldPuns
      - RecordWildCards