name: haskell-scaffold
author: Nikolai Paul <nikolai.paul@zenex.de>
version: 0.0.0
license: MIT

dependencies:
- base
- protolude
- containers

executables:
  haskell-scaffold:
    source-dirs: src
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Wcompat
      - -Wincomplete-record-updates
      - -Wincomplete-uni-patterns
      - -Wpartial-fields
      - -Widentities
      - -Wredundant-constraints
      - -Wcpp-undef
      - -Wmissing-export-lists
      - -Wmonomorphism-restriction
    default-extensions:
      - NoImplicitPrelude
      - OverloadedStrings
      - NamedFieldPuns
      - RecordWildCards
      - DuplicateRecordFields